# Font
font_family monospace
font_size 12
font_feature_cv01 1

# Window
window_padding_width 8
window_margin_width 0

# Cursor
cursor_shape beam
cursor_beam_thickness 1.5
cursor_trail 3

# Bell
enable_audio_bell no
visual_bell_duration 0.5
visual_bell_color #ffffff

# Scrollback
scrollback_lines 10000

# --- Colors - Catppuccin Macchiato ---
foreground           #cad3f5
background           #24273a
selection_foreground #24273a
selection_background #f4dbd6

# Cursor colors
cursor               #f4dbd6
cursor_text_color    #24273a

# URLs
url_color            #91d7e3

# ANSI Colors
# Black
color0 #494d64
color8 #5b6078
# Red
color1 #ed8796
color9 #ed8796
# Green
color2  #a6da95
color10 #a6da95
# Yellow
color3  #eed49f
color11 #eed49f
# Blue
color4  #8aadf4
color12 #8aadf4
# Magenta
color5  #f5bde6
color13 #f5bde6
# Cyan
color6  #8aadf4
color14 #8aadf4
# White
color7  #a5adcb
color15 #cad3f5

# Opacity
background_opacity 0.9

# Shell
shell /usr/bin/bash

# Confirmation settings
confirm_os_window_close 0
paste_actions quote-urls-at-prompt
