general {
    lock_cmd = pidof hyprlock || hyprlock       # Commande pour verrouiller
    before_sleep_cmd = loginctl lock-session    # Verrouiller avant la mise en veille
    after_sleep_cmd = hyprctl dispatch dpms on  # Rallumer l'écran au réveil
}

listener {
    timeout = 300                                # 5 minutes
    on-timeout = loginctl lock-session           # Verrouille l'écran
}

listener {
    timeout = 600                                # 10 minutes
    on-timeout = hyprctl dispatch dpms off       # Éteint l'écran
}
