# ----------------------------------------------------- 
# HYPRLAND MODULAIRE
# ----------------------------------------------------- 

# 1. Variables globales (on les garde ici pour un accès rapide)
$terminal = kitty
$fileManager = dolphin
$menu = rofi -show drun

# 2. Chargement des modules
source = ~/.config/hypr/conf/monitors.conf
source = ~/.config/hypr/conf/appearance.conf
source = ~/.config/hypr/conf/autostart.conf
source = ~/.config/hypr/conf/windowrules.conf
source = ~/.config/hypr/conf/keybinds.conf
source = ~/.config/hypr/conf/input.conf

# 3. Env vars (Optionnel, si tu en as pour ton GPU par exemple)
env = XCURSOR_SIZE,24
env = HYPRCURSOR_SIZE,24
