# On précharge l'image en mémoire
preload = /home/joe/Images/shaded-tardis.png

# On l'applique sur l'écran du haut (Iiyama)
wallpaper = HDMI-A-1,/home/joe/Images/shaded-tardis.png

# On l'applique sur l'écran du bas (PC Portable)
wallpaper = eDP-1,/home/joe/Images/shaded-tardis.png

# Pour économiser de la batterie
splash = false
