# exec-once = $terminal
# exec-once = nm-applet &
# exec-once = waybar & hyprpaper & firefox
exec-once = awww-daemon
exec-once = sleep 0.5 && awww img ~/Images/shaded-tardis.png
exec-once = waybar
exec-once = wl-paste --type text --watch cliphist store # Sauvegarde le texte
exec-once = wl-paste --type image --watch cliphist store # Sauvegarde les images
exec-once = eww daemon && eww open clock
