# --- Gestion du Fond d'écran (Awww) ---
exec-once = awww-daemon
exec-once = sleep 0.5 && awww img ~/Images/shaded-tardis.png

# --- Barre d'état et Notifications ---
exec-once = waybar
exec-once = swaync

# --- Presse-papiers (Cliphist) ---
exec-once = wl-paste --type text --watch cliphist store 
exec-once = wl-paste --type image --watch cliphist store 

# --- Widgets et UI (Eww) ---
# On s'assure que le démon est bien prêt avant d'ouvrir la clock
exec-once = eww daemon && sleep 1 && eww open clock

# --- Gestion de l'énergie et Idle ---
exec-once = hypridle

# --- Applets Système (Optionnel mais recommandé) ---
exec-once = nm-applet --indicator
exec-once = blueman-applet
