# L'écran externe (Iiyama) au-dessus
# Résolution 1920x1200, position 0x0
monitor = HDMI-A-1, 1920x1200@60, 0x0, 1

# L'écran du PC portable en dessous
# Résolution 1920x1080, décalé de 1200 pixels vers le bas
monitor = eDP-1, 1920x1080@60, 0x1200, 1
